### ISSUE TITLE
Feature request - icon toggle status & exclude pages

### ISSUE THREAD

**Issue by ayutheos** [turnermm/sectiontoggle#11]
Hi,

Loving this plugin, but would be great if the following functionalities could be added to the plugin:
- Icon to indicate toggle status (currently the icon stays the same whether section is toggled or not)
- Option to exclude namespaces/pages

Thanks!

**Comment by turnermm** [comment]
Please test this branch:
https://github.com/turnermm/sectiontoggle/archive/no_toggle.zip

It has two new options:  1) exclude listed namespaces, 2) exclude listed page ids from have toggles

**Comment by whytong** [comment]
It seems to be working but with some caveats. The page I added "~~stoggle_buttons~~" is fully closed. The start page is open. But header line H6 H5 (with two =") are open while those with >2 = are closed.

**Comment by turnermm** [comment]
I don't follow.  Explain in full detail.

**Comment by whytong** [comment]
Sorry for the delay in response.

Configuration options are default:
platform:all
type:none
name: null
headers: h4
suspend: unchecked
xcl_headers: unchecked
tablet_toggle:checked
The rest are either null or unchecked.

There is the issue: When there are H5 headings in the page under an H4 heading, headings marked with H1-H4 are all toggles but the H5 headings within that H4 heading are open and they are not toggles, and not collapsed when clicking the H4 heading. That makes it look weird. The ideal situation should be that anything within a collapsed heading should also be invisible. In the case of Wikipedia on mobile, the introductory text of each page under the page title is visible but all other texts within each section are not.

**Comment by turnermm** [comment]
Set this

  headers: h4

to

headers: h5

**Comment by whytong** [comment]
Yes. That works for H5. But then I have to set "headers" to h6 if I have H6 headings.

The more ideal situation is something similar to Wikipedia toggles. Here is the scenario:
in the following case. "H4 heading 1" is a toggle, but "H4 heading 2" is not, instead, the two H5 headings show up as toggles. 

=== H4 heading 1 ===
Text block 1
=== H4 heading 2 ===
== H5 heading 1 ==
text block in h5-2
== H5 Heading 2 ==
text block in h5-2

**Comment by turnermm** [comment]
https://www.dokuwiki.org/wiki:syntax#sectioning

**Comment by trailjeep** [comment]
I too would like to see part 1 implemented:
> Icon to indicate toggle status (currently the icon stays the same whether section is toggled or not)
I modified script.js to:
```diff
--- script.js.ORG       2019-09-18 14:54:08.835693147 -0400
+++ script.js   2019-09-18 14:57:23.695693252 -0400
@@ -32,7 +32,7 @@
                 };     
           
                 this.onmouseover = elem.style.cursor='pointer';
-                var $class = 'header__' + index;
+                var $class = 'st_closed header__' + index;
                 jQuery(this).addClass($class);         
                 
                 /* add toggle icon and  hide data below this header */
@@ -49,7 +49,7 @@
 checkheader : function (el,index) {
    var classes = el.getAttribute('class');  
   if(!classes.match(/(header__\d+)/)) return;
-  
+   jQuery(el).toggleClass('st_closed st_opened');
    jQuery(el).next().toggle();
   
 },
```
and style as such:
```css
[class*="header__"] > img { display: none; }
[class*="header__"].st_closed::before { content: url('https://api.iconify.design/el:chevron-down.svg?color=%23ccc&height=16'); vertical-align: middle; padding-right: 0.25em; }
[class*="header__"].st_opened::before { content: url('https://api.iconify.design/el:chevron-up.svg?color=%23ccc&height=16'); vertical-align: middle; padding-right: 0.25em; }
```
